name: 'Generate API documentation using local LLMs'
description: 'Generate API documentation from Java/Kotlin/Groovy files'
inputs:
  repository_url:
    description: 'https://github.com/xyproto/apidoc-action'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository_url }}
